name: iil-python-tools
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss
  - ipykernel
  - seaborn
  - tqdm
  - fire
  - textual>=0.27
  - pytorch=1.13
  - pip
  - pytest
  - pip:
    - mido
    - python-rtmidi
    - python-osc
    - taichi
    - sounddevice
    - sf2utils
