name: iil-python-tools
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.13
  - ipykernel
  - seaborn
  - tqdm
  - fire
  - textual
  - pip
  - pip:
    - mido
    - python-rtmidi
    - python-osc
    - taichi
    - sounddevice
